### PR TITLE
Testing tweaks

### PR DESCRIPTION
**Pull request by MrFondant**
Follow up to #1 with some small changes

### CODE REVIEW

**Comment by kazsaj** [comment]
Do you have an example of `INPUT_COMPOSER_INSTALL_ARGUMENTS` ? I wouldn't expect there to be need for any quoting, on the contrary - if there are multiple values in there it could break stuff, e.g.
```
# setting up a variable I will re-use
kazsaj@mATX:~/git/_frontend/vc-sdk$ export COMPOSER_ARGS="--no-dev --ignore-platform-reqs"

# using variable without quoting resulting in every part being treated as a separate arg
kazsaj@mATX:~/git/_frontend/vc-sdk$ composer install ${COMPOSER_ARGS}
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Generating autoload files

# using quotation, which results in it being treated like a single arg
kazsaj@mATX:~/git/_frontend/vc-sdk$ composer install "${COMPOSER_ARGS}"

                                                                
  The "--no-dev --ignore-platform-reqs" option does not exist.  
                                                                

install [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--dry-run] [--dev] [--no-suggest] [--no-dev] [--no-autoloader] [--no-progress] [--no-install] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--] [<packages>...]
```

**Comment by kazsaj** [comment]
I found the arguments in here: https://github.com/DocnetUK/venditan-commerce/pull/12688/files#diff-ea12f60188cdd90bc99e5d0af2eb91647bbe4a9199176aa1ec5240f65efed510R18

But as far as I can tell the extra quoting should break this.

**Comment by MrFondant** [comment]
> edit: I just realised this behaviour might be different for different shells. E.g. the testing above was done on bash 5.0, but in zsh COMPOSER_ARGS is quoted automatically in both cases (so always results in the behaviour like in the second case)

Yes, I'm wondering if this is causing your issue. When I test locally, I can pass an extra argument for Composer, from the .yaml in the VMC repo. I can see then Composer responding to that argument when the runner starts.

I use zsh on local and am using https://github.com/nektos/act to test, using `act --job php-unit --rebuild` from the VC repo (also temporarily switching the action to my fork, and adding a GH token).

**Comment by MrFondant** [comment]
I plan to introduce this cautiously into VC - one workflow at a time starting with the PHP Unit runner. Although there is a local testing setup of sorts, it's not a full replica of our setup.

**Pull request merged**
